### ISSUE TITLE
Make the cruft update workflow smarter

### ISSUE THREAD

**Issue by Cadair** [sunpy/package-template#72]
```[tasklist]
### Tasks
- [ ] If there are conflicts then we should open the PR as draft and put a comment in the body
- [ ] If the workflow is run again before the PR is merged it should update the existing PR.
- [ ] If the update PR is closed without merging or maybe a comment is left a reject PR should be opened
- [ ] Don't open a PR if the only diff is the cruft.json
```

**Comment by Cadair** [comment]
Also it shouldn't open a PR if nothing but the commit hash has changed, it just makes pointless noise.
